Add line highlighting to code blocks
getzola/zola pull request #1131
Opened 2020-08-15 14:59 UTC by Darksonn

I'm posting this PR now to get some initial review on the approach. I have not yet been able to test the feature due to #1130.

This PR works on #127 and was discussed [here][1].

[1]: https://zola.discourse.group/t/customize-syntax-highlighting/543

2020-08-17 16:46 UTC, Keats requested changes
I've tried it on the docs but it seems the highlight isn't doing anything?

2020-08-17 16:46 UTC, Keats commented on components/rendering/src/markdown/codeblock.rs
> +                .unwrap_or(Color { r: 0xff, g: 0xff, b: 0, a: 0 });
Can we use 255 here?

2020-08-17 16:46 UTC, Keats commented on components/rendering/src/markdown/fence.rs
> +impl Range {
Can we have only one impl block? I would probably move all of it to `codeblock.rs` at the root of the folder rather than in a sub markdown folder.

2020-08-22 14:43 UTC, Darksonn commented on components/rendering/src/markdown/fence.rs
> +impl Range {
The new changes removed the other impl block. Do you want me to move this one?

2020-08-27 18:29 UTC, Keats requested changes
It wooorks, very nice!

The only issue I have with the feature is that the highlight doesn't take the full line and doesn't highlight empty lines. It would be *very* nice if it did but not mandatory for the initial version.

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/codeblock.rs
> +    num_lines: usize,
can you document what that is?

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/codeblock.rs
> +struct StyledIdx {
Idx of what?

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/codeblock.rs
> +fn get_str_if_vec_is(idx: Option<&StyledIdx>, vec_idx: usize) -> Option<usize> {
this function is not super clear

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/codeblock.rs
> +// This function assumes that the line boundaries is sorted.
are sorted or `line_boundaries`

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/fence.rs
> +    fn next(&mut self) -> Option<FenceToken<'a>> {
why not impl Iterator?

2020-08-27 18:29 UTC, Keats commented on components/rendering/src/markdown/fence.rs
> +impl Range {
I would move the struct here and it should be good enough

2020-08-28 19:53 UTC, Darksonn commented
I will address the various comments later when I have time to code.

> The only issue I have with the feature is that the highlight doesn't take the full line and doesn't highlight empty lines. It would be very nice if it did but not mandatory for the initial version.

It is unclear how the generated html should even look to support that. The same applies for line numbers.

2020-08-29 06:14 UTC, Keats commented
> It is unclear how the generated html should even look to support that. The same applies for line numbers.

Yep, not for this patch. We can figure it out later.

2020-09-02 10:51 UTC, Darksonn commented
I have addressed all concerns.

2020-09-02 17:53 UTC, Keats commented
Looks great! I will merge that in the 0.13 release of Zola instead of 0.12 since I want to test it a bit more.
Could you add some test coverage on that?

2020-09-02 18:36 UTC, Darksonn commented
I wrote some tests and came up with a neat macro for making the tests readable.

2020-09-08 19:31 UTC, Keats approved these changes

2020-09-08 19:32 UTC, merged

2020-09-08 19:32 UTC, Keats commented
Amazing thanks!

2020-10-02 20:41 UTC, phil-opp commented
I just tried to use this feature, but the highlighting is very subtle. Is there a way to configure the highlighting color or is it hardcoded by the syntax highlighting theme?

2020-10-02 20:46 UTC, Darksonn commented
It is hard-coded to the `line_highlight` attribute of the theme.

2020-10-02 20:56 UTC, phil-opp commented
Thanks for the quick reply!

@Keats Would you be open to a pull request that makes the highlighting color configurable? My goal is that the lines immediately stand out, which is not the case for most dark themes right now.

2020-10-03 08:39 UTC, Keats commented
It's very subtle right now because it doesn't really work like an editor and only highlights they keywords and not the whitespace.
I would prefer fixing that part first to see if it's better before making it configurable.

2020-10-03 09:08 UTC, phil-opp commented
At least for the `visual-studio-dark` theme, whitespace is already highlighted too:

![image](https://user-images.githubusercontent.com/1131315/94987408-8ddff580-0566-11eb-89c4-c44284bd4c63.png)

The `let vga_buffer = […]` line is highlighted here. However, the contrast is very low, so the highlighting doesn't really stand out.

I would like to configure it more in this direction:

![image](https://user-images.githubusercontent.com/1131315/94987712-9df8d480-0568-11eb-8319-bb2f048d99b7.png)

2020-10-03 15:54 UTC, vednoc commented
@phil-opp I'm overriding the highlight color in CSS, like so: 

```css
pre [style*="background-color:#eddab5"] {
    background-color: #0f03 !important;
}
```
Note that `!important` is necessary because that's the only way you can override inline styles.

2020-10-03 18:54 UTC, Keats commented
That's one way, probably nicer than config.toml.
Can someone check the theme in Sublime Text3 to see how the highlighting looks like?