Add minify support
getzola/zola pull request #1146
Opened 2020-08-24 08:44 UTC by augustinreille

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

Closes #542

2020-08-24 08:55 UTC, Keats requested changes

2020-08-24 08:55 UTC, Keats commented on components/config/src/config/mod.rs
> +    pub minify: bool,
this needs to be `minify_html`

2020-08-24 08:55 UTC, Keats commented on components/site/src/lib.rs
> +        }
you need to have the same code everywhere we are rendering a template: section and taxonomies at least

2020-08-24 08:55 UTC, Keats commented on components/site/src/lib.rs
> +                    eprintln!("{}", error_type.message())
we should bail rather printing to stderr

2020-08-24 10:56 UTC, augustinreille commented
Gone to WIP status because of a problem found with `minify-html`.

It appears to turn :
`<link href="http:&#x2F;&#x2F;areille.com&#x2F;style.css" rel="stylesheet">`
into :
`<link href=http:%%areille.com%style.css rel=stylesheet>`

2020-08-26 14:09 UTC, augustinreille commented
@Keats this is ready for review now.

2020-08-26 18:21 UTC, Keats requested changes
I think we should move the minification to `write_content` so we can't forget it and no need to repeat ourselves everywhere

2020-08-26 18:21 UTC, Keats commented on components/site/src/lib.rs
> +        if self.config.minify_html {
can you reverse the condition so it's not indented? eg `if not self.config.minify_html { return Ok(html) } ..`

2020-08-26 18:21 UTC, Keats commented on components/site/src/lib.rs
> +        let minified_content = self.minify(content).expect("Couldn't minify html file");
we need to remove the expect and bubble up the error

2020-08-26 18:21 UTC, Keats commented on components/site/src/lib.rs
> +        let minified_content = self.minify(content).expect("Couldn't minify html file");
same here, need to remove the expect

2020-08-26 18:21 UTC, Keats commented on components/site/src/lib.rs
> +        let minified_content = self.minify(content).expect("Couldn't minify html file");
same here and everywhere.

2020-08-26 18:55 UTC, augustinreille commented
I moved the `minify()` call inside `write_content()`. Hope that it is ok now !

2020-08-26 18:59 UTC, Keats commented
Seems good, can you add a couple of tests for the minified output?

2020-08-26 20:25 UTC, augustinreille commented
I added a test for `index.html`. Please let me know if this is not enough and I will add some tests for other files.

2020-08-28 17:39 UTC, Keats approved these changes

2020-08-28 17:39 UTC, Keats commented
Thanks! I'll bump the pinned version myself for the build to pass

2020-08-28 17:39 UTC, merged