Add Cloudflare Pages support to README
getzola/zola pull request #1396
Opened 2021-03-08 00:43 UTC by rita3ko

Demo: https://my-zola-project.pages.dev/ !

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [ ] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

2021-03-08 08:02 UTC, Keats requested changes
How does it work? Could you add some docs for it?

2021-03-08 08:02 UTC, Keats commented on README.md
> +| Cloudflare Pags support         | ![yes] | ![no]  | ![yes] | ![yes]  |
pages

2021-03-14 15:54 UTC, codeandmedia commented
Sorry to interrupt you, I just have tested Pages, it looks pretty easy and tremendously fast. It's a worker on Cloudflare infrastructure that contains Zola binary and upload an output to CF storage. Cloudflare have HowTo here: https://developers.cloudflare.com/pages/how-to/deploy-a-zola-site . 

@Rita3ko first of all, many thanks Cloudflare team for this cool service. I guess it would be useful to add Cloudflare here (https://www.getzola.org/documentation/deployment/overview/) and we already have all what it needed, some screenshots might improved the text. I can help with that, but don't know how to do it properly.

2021-03-17 08:14 UTC, Keats commented
@codeandmedia could you do a PR explaining how to get set up in the docs? Even if it's just a link to the cloudflare page

2021-03-17 10:05 UTC, codeandmedia commented
> 
> 
> @codeandmedia could you do a PR explaining how to get set up in the docs? Even if it's just a link to the cloudflare page

done! https://github.com/getzola/zola/pull/1414

2021-03-22 18:21 UTC, merged