This PR modifies how the parser will parse the following markdown:
getzola/zola pull request #1475
Opened 2021-05-22 18:45 UTC by NieDzejkob

```
{% first() %}

  {% second() %}

  {% end %}

{% end %}
```

Previously, this would parse as the shortcode `first` with `{% second() %}` as the body, all followed by the text `{% end %}`. Now it nests properly.

Together with the already-merged PR #1358, this fixes issue #515.

2021-05-23 11:58 UTC, Keats commented
Thanks! Can you add some tests?

2021-05-23 17:24 UTC, NieDzejkob commented
I'm not sure what's the best way to test this. I tried the following:
```rust
    #[test]
    fn recursive_shortcodes() {
        let mut tera = Tera::default();
        let md = MarkdownFilter::new(PathBuf::new(), Config::default(), HashMap::new()).unwrap();
        tera.register_filter("markdown", md);
        tera.add_raw_template("shortcodes/outer.html", "This is the outer shortcode. {{ body | markdown | safe }}").unwrap();
        tera.add_raw_template("shortcodes/inner.html", "We're inside! {{ body | markdown | safe }}").unwrap();
        let res = render_shortcodes("{% outer() %} One! {% inner() %} Two! {% end %} Three! {% end %} Fin.", &tera);
        assert_eq!(res, "TODO");
    }
```

This fails for the same reason #1358 was necessary - the markdown filter as constructed here cannot see the `inner` filter. I don't see how to mock the filesystem like this so it affects `MarkdownFilter` :/

2021-05-24 06:24 UTC, Keats commented
You can probably skip the `markdown` filter in the test and have only the shortcodes for the test

2021-05-24 18:08 UTC, NieDzejkob commented
Okay, I've added a test.

2021-06-06 21:20 UTC, NieDzejkob commented
Did you have a chance to look at this?

2021-06-07 07:52 UTC, Keats commented
Not yet sorry, I will have a look this week.

2021-06-14 18:14 UTC, Keats requested changes

2021-06-14 18:14 UTC, Keats commented on components/rendering/src/shortcode.rs
> +        assert_eq!(res, "<pre data-shortcode>This is the outer shortcode One! {% inner() %} Two! {% end %} Three! outer ends here</pre> Fin.");
I would have expected that to error since `inner` is not defined and we only render shortcodes once so `render_shortcode` should handle the recursion

2021-06-14 18:16 UTC, NieDzejkob commented
The inner shortcode will be rendered if the user passes the body through
the `markdown` filter.

2021-06-16 17:16 UTC, Keats commented
Ok had another look.
I think the test should create the temp dir and the shortcode files so the markdown filter is aware of it so we can test the actual behaviour.
To create temp files, see https://github.com/getzola/zola/blob/next/components/templates/src/global_fns/images.rs#L141-L150 and just pass the `dir` as base path to the MarkdownFilter, which will load the Tera templates.

Sorry for the confusion

2021-07-10 18:19 UTC, Keats commented
@NieDzejkob ping

2021-07-11 15:42 UTC, NieDzejkob commented
Thanks for the ping! I edited the test, but it still fails — the inner call to `markdown` doesn't see the filter. I don't exactly see why that is. Could you take a look?

2021-07-12 18:36 UTC, Keats commented
The issue is:
```
        let tera = load_tera(&path, &config).map_err(tera::Error::msg)?;
```
 in the `MarkdownFilter::new`. This means it essentially creates a new instance of Tera which will have the shortcodes but this instance will not have the markdown filter since it hasn't been registered.

I don't know what to do about that tbh.

2021-07-12 18:46 UTC, NieDzejkob commented
Perhaps the markdown filter shouldn't create its own instance of Tera at all? The cleanest solution would be to make `tera::Filter::filter` take a reference to the `Tera` instance, though if that's unacceptable, we could make the `Tera` variable in `struct Site` an `Arc<Tera>`, and keep a `Weak<Tera>` in the filter.

2021-07-13 06:34 UTC, Keats commented
> The cleanest solution would be to make `tera::Filter::filter` take a reference to the `Tera` instance

That would have to be for Tera v2 so not anytime soon.

We can also keep Arc<Tera> in the filter no?

2021-07-13 11:26 UTC, NieDzejkob commented
> We can also keep Arc in the filter no?

AFAICS, keeping a full `Arc` in the filter (as opposed to `Weak`) would create a cycle and leak memory. I'm not sure whether a new instance of Tera gets created for each rebuild in a `zola serve` session, but if not, this cycle would indeed be harmless, and we could use an `Arc` directly.

2021-07-14 11:56 UTC, Keats commented
> I'm not sure whether a new instance of Tera gets created for each rebuild in a zola serve session, but if not, this cycle would indeed be harmless, and we could use an Arc directly.

On template changes other than shortcodes, it only re-render the pages but re-uses the instance. On any other change content/shortcode change, it will rebuild completely the `Site` struct from scratch which contains the Tera instance.
Now that you mention it, I'm using `Arc` in a couple of functions and I'm wondering if https://github.com/getzola/zola/issues/1515 is a symptom.

2021-08-24 07:41 UTC, Keats commented
Closing as it will be addressed by #1564 in the end. Thanks though @NieDzejkob !

2021-08-24 07:41 UTC, closed without merging