Apply orientation transformation based on EXIF data
getzola/zola pull request #1912
Opened 2022-06-26 14:03 UTC by bemyak

Some images (especially photos) are stored with incorrect orientation. There is a EXIF metadata attached, so browsers and image viewers know how to display it properly.

Unfortunately, when applying transformations, this metadata isn't copied (see https://github.com/image-rs/image/issues/1045#issuecomment-733790099), so the only way to fix it is to apply the corresponding transform on the Zola's side.

---

## Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes

* [X] Are you doing the PR on the `next` branch?
* [?] Have you created/updated the relevant documentation page(s)? (Should I?)

2022-06-26 16:17 UTC, bemyak commented
Just to clarify: all 8 new images are differently oriented, but they have the correct EXIF tag set, so the browser displays them properly. The issue can be reproduced if you try to `resize_image` any of them (except the first one, it has no rotation).

2022-07-04 20:54 UTC, Keats requested changes
That seems good. The GH preview shows all image with the top left being red, can you add a detail in one of the test what is the exif data in each?

2022-07-04 21:51 UTC, bemyak commented
The number in the image filename indicates the value of the `Orientation` tag. For `exif_0.jpg` the tag is not set. I've added the corresponding descriptions.

For reference, the image description is taken from an output of this command:
```bash
$ exiftool -Orientation exif_5.jpg
Orientation                     : Mirror horizontal and rotate 270 CW
```

You can get the raw value like this:
```bash
$ exiftool -b -Orientation exif_5.jpg
5
```

2022-07-06 19:22 UTC, Keats requested changes
Small nits.
Do you have an example site where Zola was displaying things incorrectly after an op? Just to easily try this branch somewhere

2022-07-06 19:22 UTC, Keats commented on components/imageproc/src/lib.rs
> +    let file = std::fs::File::open(path).unwrap();
Can we avoid unwrap?

2022-07-06 19:22 UTC, Keats commented on components/imageproc/src/lib.rs
> +    let exif = match exif {
you can put ` exif_reader.read_from_container(&mut buf_reader)` after `match` and you avoid one variable named exif

2022-07-06 20:48 UTC, bemyak commented
> Do you have an example site where Zola was displaying things incorrectly after an op? Just to easily try this branch somewhere

Yep, you clone [this](https://gitlab.com/bemyak/blog.git), and then open `/ru/finland/tuomarilanrinne/` url. The first image (with a baby) is oriented incorrectly, but if you click on it, the original will be opened, which didn't pass the transformation, so it displays correctly.

To build the blog you'll probably need [git-lfs](https://git-lfs.github.com/) installed and zola `next`, it doesn't build on stable because of https://github.com/getzola/zola/issues/1904

Also when trying different versions remember to delete `static/processed_images` dir.

2022-07-06 20:51 UTC, bemyak commented
Alternatively, you can just use the test images from this PR, it'll probably be faster. The blog is pretty heavy.

2022-07-07 21:16 UTC, Keats approved these changes
Perfect, thanks!

2022-07-07 21:19 UTC, merged