Get term fn
getzola/zola pull request #1964
Opened 2022-08-13 21:08 UTC by scouten

As discussed in #1897, this adds a new `get_term` global function which returns a single `TaxonomyTerm` item instead of the entire site. In the personal site discussed in that issue, this results in a 4x improvement in rendering speed (5.4s vs 22.1s).

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

2022-08-16 06:51 UTC, Keats reviewed
All good except the name and that it needs a rebase

2022-08-16 06:51 UTC, Keats commented on docs/content/documentation/templates/overview.md
> +### `get_term`
can we call it `get_taxonomy_term`?

2022-08-17 17:52 UTC, scouten-adobe commented on docs/content/documentation/templates/overview.md
> +### `get_term`
Sure. I'll rename in next day or so.

2022-08-17 22:52 UTC, scouten commented
@Keats updated as requested.

2022-08-22 21:29 UTC, Keats requested changes

2022-08-22 21:29 UTC, Keats commented on docs/content/documentation/templates/overview.md
> +`include_pages` (optional) default to true. If false, the `pages` item in the `TaxonomyTerm` is replaced with `page_count`, an integer with the number of pages for this term.
looking at it again, I think `page_count` should be additional field that is always passed and this arguments just make pages an empty array.

2022-08-24 20:29 UTC, Keats approved these changes

2022-08-24 20:29 UTC, merged

2022-08-24 20:29 UTC, Keats commented
Thanks!