fix: do not check the same url more than once
getzola/zola pull request #2301
Opened 2023-09-12 14:03 UTC by peterprototypes

This is a fix for https://github.com/getzola/zola/issues/2298

Before:

![DeepinScreenshot_select-area_20230912162708](https://github.com/getzola/zola/assets/7164437/7ae418c9-2299-4910-ab5e-cce909db246d)

After:

![DeepinScreenshot_select-area_20230912162728](https://github.com/getzola/zola/assets/7164437/be7cc7e0-8833-437d-9cd0-ce092f637d57)

I've used the https://github.com/organicmaps/organicmaps.github.io/ repo for the before and after tests.

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

2023-09-12 20:06 UTC, Keats requested changes

2023-09-12 20:06 UTC, Keats commented on components/site/src/link_checking.rs
> +            );
I think using the entry api would be nicer here

2023-09-13 06:53 UTC, peterprototypes commented
@Keats looks like me and @biodranik worked on the same thing. I think his solution is a bit easier to follow, as it avoids the complexity of a nested HashMap. The only difference in end result is that I changed the output to show the number of unique external links instead of the total number of links.

2023-09-13 07:17 UTC, biodranik commented
Printing the real number of _unique_ urls that are checked is a good idea. 

In my approach failures are also printed for each page where the same link was used, so you can see how often the failed link is used, and on which pages. Is it the same for your implementation?

2023-09-13 08:03 UTC, peterprototypes commented
> Printing the real number of _unique_ urls that are checked is a good idea.
> 
> In my approach failures are also printed for each page where the same link was used, so you can see how often the failed link is used, and on which pages. Is it the same for your implementation?

Yes, it's the same. I also clone the result from the first checked link to all messages.

2023-09-13 17:50 UTC, biodranik commented
Learning Rust in this way is a lot of fun! I've also updated my PR #2305, @Keats WDYT?

2023-09-13 19:21 UTC, Keats commented
I think #2305 approach is a bit neater

2023-09-13 19:29 UTC, closed without merging

2023-09-13 19:29 UTC, peterprototypes commented
> I think #2305 approach is a bit neater

Agreed :+1: