Avoid unnecessary checking for already checked links
getzola/zola pull request #2305
Opened 2023-09-12 16:57 UTC by biodranik

Fixes #2298

For localized [Organic Maps zola site](https://github.com/organicmaps/organicmaps.github.io/) the time for `zola check` link checking has reduced from 3 minutes to less than 1 minute.

2023-09-13 19:21 UTC, Keats requested changes

2023-09-13 19:21 UTC, Keats commented on components/site/src/link_checking.rs
> +        "Checking {} unique link(s) out of {} total external link(s) on all pages. Skipping {} external link(s).{}",
I don't know if we need the distinction between unique vs total. We can keep the current message but show the unique number

2023-09-13 19:21 UTC, Keats commented on components/site/src/link_checking.rs
> +                                if checked_links.contains_key(external_link) {
you can use `if let Some(...) = checked_links.get(external_link)` which would be cleaner

2023-09-13 21:11 UTC, biodranik commented
@Keats done, PTAL

2023-09-14 16:23 UTC, Raymi306 commented
To fix the CI issue, you can run `cargo fmt`

2023-09-14 16:59 UTC, biodranik commented
Thanks! Also `brew install rustfmt` is needed first :) PTAL.

2023-09-17 19:49 UTC, Keats approved these changes

2023-09-17 21:30 UTC, Keats commented
Some of the code can be cleaned up a bit, I'll post a link to the commit after doing it.

2023-09-18 05:33 UTC, biodranik commented
@Keats Thanks! You can also leave suggestions if it's easier )

2023-09-24 20:02 UTC, merged