Match `<!--more-->` in addition to `<!-- more -->`
getzola/zola pull request #2397
Opened 2024-01-01 21:28 UTC by clarfonthey

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?
* [x] Are you doing the PR on the `next` branch?

I noticed this when trying to migrate a few WriteFreely posts to Zola. WriteFreely uses `` when added via the rich-text editor, whereas Zola was picky about the spaces around the tags. I replaced the check with a regex so that spaces and case don't matter any more.

2024-01-02 09:46 UTC, Keats commented
Can you add a test?

2024-01-03 20:34 UTC, clarfonthey commented
Sorry for taking a bit to get to this-- a lot of my focus was on trying to get my particular static site setup working, and I was just submitting PRs for the changes I made that I thought would be reasonable to upstream.

I added some tests directly to the markdown parser, since it seems that most of the current summary-splitting tests are in the content itself. This way, it's a little closer to a unit test than an integration test.

Unfortunately, newline-split `<!-- more -->` would not work under this setup due to the way `pulldown-cmark` works, and I filed a bug to see if upstream would be interested in fixing this. But at least for now, allowing extra spaces between the more tags, and case-insensitivity, seems like a net improvement.

2024-01-07 13:19 UTC, Keats commented on components/markdown/src/markdown.rs
> +                    dbg!(&text);
you can remove that

2024-01-07 13:22 UTC, Keats requested changes

2024-01-07 13:22 UTC, Keats commented on components/markdown/src/markdown.rs
> +                    if MORE_DIVIDER_RE.is_match(&text) {
you should check first if `has_summary` is already set to true, otherwise you might push multiple continue reading event

2024-01-07 19:23 UTC, Keats approved these changes

2024-01-07 19:23 UTC, merged