Implement zola serve --store-html
getzola/zola pull request #2750
Opened 2024-12-27 14:44 UTC by ppom0

Fixes #2377

2024-12-28 19:52 UTC, Keats requested changes

2024-12-28 19:52 UTC, Keats commented on components/site/src/lib.rs
> +    pub fn enable_serve_mode(&mut self, both: bool) {
there's an enum for it, use it in the params instead of a bool

2024-12-28 19:52 UTC, Keats commented on src/cli.rs
> +        #[clap(short = 'H', long)]
I think only having long here is fine

2025-01-04 15:40 UTC, ppom0 commented on components/site/src/lib.rs
> +    pub fn enable_serve_mode(&mut self, both: bool) {
Does the new commit correspond to your idea?

I can also squash it onto the previous commit.

2025-01-04 21:58 UTC, Keats approved these changes
Yep perfect

2025-01-04 22:00 UTC, Keats commented
Looks like legit tests failures

2025-01-08 19:23 UTC, ppom0 commented
Yes indeed!
Are you ok with the tests just testing serve without the `--store-html` option?

2025-01-09 10:00 UTC, Keats commented
Yes that's fine

2025-01-09 10:00 UTC, merged