Fix documentation typos and minor changes:
getzola/zola pull request #278
Opened 2018-04-02 00:38 UTC by andradei

- Fix some typos
- Some small changes to documentation to make it more clear
- Change the themes list from text to links
- Remove whitespace at the end of some lines

2018-04-03 08:49 UTC, Keats requested changes
Small typo but looks good otherwise, thanks!

2018-04-03 08:49 UTC, Keats commented on docs/content/documentation/content/section.md
> +contains a `index.md` file and is actuallya page with assets.
space between actually and a

2018-04-03 16:25 UTC, andradei commented on docs/content/documentation/content/section.md
> +contains a `index.md` file and is actuallya page with assets.
Good eye. Fixed.

2018-04-09 10:14 UTC, merged

2018-04-09 10:14 UTC, Keats commented
Thanks!