Add `index page` section to documentation
getzola/zola pull request #331
Opened 2018-07-12 20:46 UTC by codesections

The current documentation does not describe how to create a index page.  I initially found this confusing, because I expected an index page to be a **page** rather than a section.  Thus, I tried to access the page content with `{{ page.content }}` and was very frustrated when I could not.

This addition clarifies that the index page is **always** a section, even if it does not have any sub-pages.  This should also help people who intend to use Gutenberg to build stand-alone webpages, rather than blogs.

(Also, please let me know if these documentation related pull requests are unwelcome/annoying.  I'm really enjoying using Gutenberg, and I feel that the best way I can help right now—given that I don't (yet) know Rust well enough to contribute code—is by suggesting ways that the documentation could be clearer to address the spots I got stuck.  But if it's not helpful, let me know and I'll knock it off.)

2018-07-14 07:57 UTC, Keats commented
I'm not sure this deserves a special page of its own. Can this be a small subection on https://www.getgutenberg.io/documentation/templates/overview/ before the built-in filter one? It is mentioned in https://www.getgutenberg.io/documentation/templates/pages-sections/#section-variables

I think it can be shorter, for example just saying that the index page is always a section and to refer to the page & section for more details.

> (Also, please let me know if these documentation related pull requests are unwelcome/annoying. I'm really enjoying using Gutenberg, and I feel that the best way I can help right now—given that I don't (yet) know Rust well enough to contribute code—is by suggesting ways that the documentation could be clearer to address the spots I got stuck. But if it's not helpful, let me know and I'll knock it off.)

Documentation updates are great, keep them coming!

2018-07-14 12:44 UTC, codesections commented
I moved the info to the `templates/overview` section as you suggested.  I agree that it's a much better fit there.

I'm not sure I kept it quite as short as you were suggesting, though.  I thought it was helpful to add a bit more context, but let me know if you think that's too much and I can cut it down a bit.

2018-07-15 08:27 UTC, Keats commented on docs/content/documentation/templates/overview.md
> +This means that you can, for example, access the content of your `_index.md` files
I would remove that sentence

2018-07-15 08:32 UTC, Keats requested changes

2018-07-15 08:32 UTC, Keats commented on docs/content/documentation/templates/overview.md
> +For example, `product_pages\with_pictures.html` is a valid template.
\ -> / to have slashes consistent

2018-07-15 08:32 UTC, Keats commented on docs/content/documentation/templates/overview.md
> +The one time that custom templates _are_ applied without being specified in the front
I would remove that paragraph, they each have a dedicated page in the docs

2018-07-15 12:39 UTC, codesections commented
I made the changes you requested.  I also moved a sentence from earlier in the page down to its own section to clarify the nature of built-in templates without adding (much) text.

2018-07-16 06:49 UTC, merged

2018-07-16 06:49 UTC, Keats commented
Thanks!