Edit docs to say that sections require an `_index.md` file
getzola/zola pull request #341
Opened 2018-07-19 18:17 UTC by codesections

This pull request provides a solution for #339.

The current version of the documentation states that sections are created automatically, but this is not correct: sections are created only if the folder contains an `_index.md` file.  This commit changes the documentation to reflect that reality and updates the surrounding
language for consistency and to explain the behaviour of `index.md files.

2018-07-19 19:52 UTC, Keats requested changes

2018-07-19 19:52 UTC, Keats commented on docs/content/documentation/content/page.md
> +`index.md`, then it will create a page with that name (without the `.md`).
`_index.md` no?

2018-07-19 19:52 UTC, Keats commented on docs/content/documentation/content/section.md
> +The index page is actually an automatically created section.  Thus, the `index.html` template
the first sentence feels a bit odd, maybe remove "automatically created" from it? Otherwise it feels like it is only automatic

2018-07-19 20:58 UTC, codesections commented
I update the pull request to address your change request re: `section.md`.

On your other change request—the one about `page.md`—I don't believe I got things backwards.  That section of the docs is discussing what happens if the user creates an `index.md` file (*not* an `_index.md` file).  If the user creates an `about/index.md` file then a *page* will be created at `about`.  This is different than if the user creates an `_index.md` file, which would create a *section*.  In typing this out, I realized that the docs could do a better job of drawing that distinction, so I updated them to clarify.

2018-07-20 07:16 UTC, merged

2018-07-20 07:17 UTC, Keats commented
Thanks!