Remove `order` and add `heavier`/`later`
getzola/zola pull request #352
Opened 2018-07-28 03:03 UTC by codesections

This commit removes the option to sort by order and also removes `page.next` and `page.previous` variables.  Instead, pages can be sorted by two methods `date` and `weight`.  The Tera `reverse` filter will reverse either of those sorts, so the old `order` behavior can be achieved by using the `reverse` filter with `weight`.

In place of the `previous`/`next` variables, this commit adds the `page.earlier`/`page.later` variables (which are set when the page is sorted by date) and the `page.heavier`/`page.lighter` variables (which
are set when the page is sorted by weight).  These variables have the advantage of not having confusing semantics when the `reverse` filter is used.

**Note**: I cannot emphasize this enough—I genuinely do not know how to program in Rust.  This was cargo-cult programing of the worst sort; I was copying lines of code with modifications that seemed to fit the context without true understanding of the surrounding code.  All the tests passed, and things looked good in manual testing, but I genuinely did not know what I was doing and want to be clear about that.

2018-07-28 14:17 UTC, Keats requested changes

2018-07-28 14:17 UTC, Keats commented on components/content/src/sorting.rs
> +                    SortBy::None => {
you can do just do `SortBy::None => ()` rather than opening braces

2018-07-28 14:17 UTC, Keats commented on components/content/src/sorting.rs
>          // Should be sorted by date
this comment seems to be lying? probably me copy/pasting a bit too much

2018-07-28 14:17 UTC, Keats commented on components/rebuild/tests/rebuild.rs
> +
remove whitespace

2018-07-28 14:18 UTC, Keats commented
It actually looks ok to me, I think you just did your first succesful Rust PR!

Only thing missing is an update to the docs but I can do it later myself if you want.

2018-07-28 18:07 UTC, codesections commented
That's great! 

I'm happy to update the docs; I intended to do so after confirming that the implementation was ok. It will probably be tomorrow before I do so, however.

2018-07-29 20:27 UTC, codesections commented
Ok, docs updated.  I updated the `section` and `page` pages, which I think are the only places that mentioned `order` (and were the only relevant pages using the word "order"), but let me know if you can think of other pages that need to be updated.

(I also merged in the changes to those pages from the master branch; the diff will show more changes than I actually made.)

2018-07-29 20:32 UTC, Keats commented
I believe there is also the page in templates about Page showing the variables available in templates

2018-07-29 21:51 UTC, codesections commented
Ok, I added that page and fixed the minor issues you mentioned in your change request. 

When revising the docs, I noticed something that seems like a bug to me, but that was beyond my current ability to fix.  Right now `populate_previous_and_next_pages` is called with the `sort_by` front-matter variable.  This means that `page.lighter` and `page.heavier` are *only* populated if the `sort_by` is set to `weight` (and the flip for `earlier` and `later`).

This doesn't seem ideal/intuitive.  It seems like someone should be able to set the `date` variable in their pages and get links to the previous/earlier pages even if they're not sorting by `date`.  I'm not really sure how we'd need to fix this, though, since we populate the variable based on adjacent pages in the sorted array.  Sorting the array multiple times could work, but that would involve loops through a sorting process that (according to comments in the code) is not very efficient.  (And, anyway, I'm not sure how to do that). 

Maybe it's not worth solving, since that use case may be rare, and it's mentioned in the docs.  But I thought I should flag it. 

Also, it's just now occurring to me while typing this comment that `populate_previous_and_next_pages` is no longer an accurate name for that function.  Would you like me to change it globally?

2018-07-30 14:32 UTC, Keats commented
`populate_previous_and_next_pages` -> `populate_siblings`?

> This doesn't seem ideal/intuitive. It seems like someone should be able to set the date variable in their pages and get links to the previous/earlier pages even if they're not sorting by date

I don't think that's a wanted behaviour: without sorting, earlier/later and lighter/heavier are meaningless since the sorting might skip pages and you will end up with a different order in the list of pages than when using earlier/later.

2018-07-31 02:44 UTC, codesections commented
Ok, name updated!

2018-07-31 13:08 UTC, merged

2018-07-31 13:09 UTC, Keats commented
Thanks!