add watch command
getzola/zola pull request #450
Opened 2018-09-28 03:20 UTC by FreeMasen

In an effort to address #213 this pull request breaks the watch functionality out from the `serve` sub-command into its own sub-command. 

This would allow someone include `gutenbreg` in their development workflow when utilizing another server. While this doesn't add proxy functionality it does solve the problem that prompted the issue.

2018-10-01 16:26 UTC, Keats commented
Hmm I am a bit hesitant to accept this as it adds a command for an issue that is not too hard to fix by adding CORS from the other end, which is only a couple of lines in Django for example.

2018-10-01 18:32 UTC, FreeMasen commented
So CORS does not feel like a solution to me.

Say I have a site built with gutenberg and I am going to serve it with nginx. I have Nginx configured to proxy pass the request for the route `/email/` to a custom server I have setup.

On one of the pages I would like to include a simple form for sending me an email, this form would have the attribute `action="/email/"` or something similar. To use `gutenberg serve` while working out the kinks in my email service, I would first need to add CORS to my email service which I only need during development. While Django might offer a great experience adding CORS, in a less featureful server framework adding CORS is not always trivial.  In addition, I would now need to setup a special configuration for my `gutenberg` template to handle the different address for these requests. This could be done with a conditional in the template like this

```jinja
<form action="{% if page.extra.debug %}http://localhost:5555/email/{% else %}/email/{% endif %}">

</form>
```

Then I would need to maintain the page variable for the front-matter on the `_index.html` for the contact page with a new property that includes `debug = false` when I push out my changes.

The other option would be to manually update this attribute, which again is not super great since it would be easy to forget.

Another situation where this command would be useful is using gutenberg in conjunction with other build tools that might offer similar function to the serve command, for example `webpack-dev-server` that offers more functionality now. For example `webpack-dev-server` implements configurations that allow for not-only forwarding request but also automatically inserting headers, compression, custom before and after behavior, route re-writing, and much more.

2018-10-02 18:58 UTC, FreeMasen commented
One more thing I will add to my above comment.

The two examples I provided in my last comment are real world experiences that I have had using `gutenberg` to build [my own webiste](https://wiredforge.com).

2018-10-18 21:24 UTC, Keats commented
How about having a `gutenberg serve --no-server` like Jekyll  does rather than `gutenberg watch`?

2018-10-19 12:14 UTC, Keats commented
Or maybe `--watch-only`, whichever sounds the best

2018-10-19 13:43 UTC, FreeMasen commented
I can do that for sure. I am at Rust Belt Rust this weekend but will probably be able to tackle it this coming week

2018-10-19 14:34 UTC, Keats commented
No worries, take your time!

2018-11-01 14:00 UTC, Keats commented
@FreeMasen are you still planning on implementing that? Looking back at the options I think I prefer `--watch-only

2018-11-01 21:48 UTC, FreeMasen commented
Sorry I got a little side-tracked. I will get to work on this today and tomorrow.

2018-11-02 07:59 UTC, Keats requested changes
One println to remove and it's ready to go, thanks!

2018-11-02 07:59 UTC, Keats commented on src/main.rs
> +            println!("watch_only: {}", watch_only);
this can be removed

2018-11-02 16:27 UTC, FreeMasen commented on src/main.rs
> +            println!("watch_only: {}", watch_only);
Sorry about that I had removed that locally but apparently forgot to push

2018-11-03 12:49 UTC, merged

2018-11-03 12:49 UTC, Keats commented
Thanks!