Implement an opportunistic watcher for all optional directories
getzola/zola pull request #453
Opened 2018-09-29 20:08 UTC by devurandom

This allows Gutenberg to start with just a config file.  All other directories
 will be picked up once they are created.  Directories which are not necessary
 will thus not cause errors.

Closes: https://github.com/Keats/gutenberg/issues/445

I expect that this will require quite some work (and documentation, which is currently completely missing) until it can be accepted, because this is one of my first pieces of Rust code. Please do not hesitate to provide feedback!

2018-09-30 08:05 UTC, Keats requested changes
That does seem like the fix is too complicated. I would have expected a ~10 lines diff as there is no need for an abstraction there imo

2018-09-30 08:05 UTC, Keats commented on src/cmd/serve.rs
> +const OPTIONAL_WATCH_DIRS: [&str; 4] = ["content", "sass", "static", "templates"];
`content` is not optional, there is nothing to do for gutenberg if it isn't there

2018-09-30 11:29 UTC, devurandom commented
"Abstraction" refers to the `OpportunisticWatcher`? My intention was to do it in a way that provides a basis for an addition to the notify crate, so more users could benefit. Sadly I'm new to Rust, so I opted to start with something that fits Gutenberg and then expand it later.

2018-09-30 15:20 UTC, Keats commented
> "Abstraction" refers to the OpportunisticWatcher

Yep, it might make sense for the `notify` crate but in Gutenberg it would be overkill imo

2018-10-10 13:34 UTC, Keats commented
@devurandom Are you interested in adding the basic fix for that issue? IE doing it like it's done for the `static` folder

2018-10-10 17:39 UTC, devurandom commented
* I could try to simplify my current code (flatten the `struct`/`impl` into local variables and regular functions). I think this is superior to having a series of `if` blocks.
* I am currently very time constrained, probably until mid November, so the chances of this happening earlier than that are slim.

2018-10-11 18:54 UTC, Keats commented
Ok, thanks! I've pushed https://github.com/Keats/gutenberg/pull/398/commits/652196969ce77f260749e4d1cefbd546f5f74b27 in the meantime, let me know if notify integrates something similar later on

2018-10-11 18:54 UTC, closed without merging