Add emphasis, strong and code support in header
getzola/zola pull request #578
Opened 2019-01-05 15:56 UTC by peng1999

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## Code changes

* [x] Are you doing the PR on the `next` branch?

---
This PR is a bug fix related to #569 , but the footnote problem is still unfixed due to some difficulty.

2019-01-05 19:46 UTC, Keats requested changes
Some nits but looks ok overall

2019-01-05 19:46 UTC, Keats commented on components/rendering/src/markdown.rs
> +    // - any of those can be in a header or not: if it's in a header
that list item is not valid anymore is it?

2019-01-05 19:46 UTC, Keats commented on components/rendering/src/markdown.rs
> +fn start_tag(temp_header: &mut TempHeader, tag: &Tag) -> bool {
can we find better name than start_tag/end_tag? it's not really clear what is it doing from the signature

2019-01-05 19:46 UTC, Keats commented on components/rendering/src/markdown.rs
> +        // Tag::Link is handled elsewhere
possible to add where?

2019-01-05 19:46 UTC, Keats commented on components/rendering/src/markdown.rs
> +            // Trivial markup generation
this comment doesn't really tell what the the lines below are doing

2019-01-06 11:06 UTC, peng1999 commented
Fixed

2019-01-07 18:19 UTC, merged

2019-01-07 18:19 UTC, Keats commented
Thanks!